name: Publish Tag
on:
  push:
    branches:
      - staging
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn
      - run: yarn build
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kgolezardi/performance-review-web
          tags: |
            type=semver,pattern={{version}}
            type=raw,enable=${{github.ref == 'refs/heads/staging' }},value=dev-${{ github.run_number }}-{{sha}}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
